--- #YAML:1.0
name:                Querylet-CGI
version:             0.141
abstract:            turn a querylet into a web application
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    CGI:                           2
    Querylet:                      0.28
    Querylet::Input:               0.22
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo SIGNES <rjbs@cpan.org>
